### ISSUE TITLE
[Bug] don't drop temporary table o$pt

### ISSUE THREAD

**Issue by AlexMorti** [oracle/dbt-oracle#12] opened 2022-05-27 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The global temporary table is not deleted after running the model due to an 

[[dbt-oracle/blob/main/dbt/include/oracle/macros/adapters.sql](https://github.com/oracle/dbt-oracle/blob/7348c2b21883c156583adc8282876c7a993eb13d/dbt/include/oracle/macros/materializations/incremental/helpers.sql#L37-L38)](https://github.com/oracle/dbt-oracle/blob/7348c2b21883c156583adc8282876c7a993eb13d/dbt/include/oracle/macros/adapters.sql#L259)

example:
create global temporary table TEST (object_id number, object_name varchar2(30)) on commit PRESERVE rows;

Such tables get bound to the session with the first insert and then this binding is ONLY removed when the session exits or by truncate. If the binding exists DDL cannot be performed on these temporary tables and if you try a DDL on such tables you would receive ORA-14452 attempt to create, alter or drop an index on temporary table already in use.

add before 
https://github.com/oracle/dbt-oracle/blob/7348c2b21883c156583adc8282876c7a993eb13d/dbt/include/oracle/macros/materializations/incremental/incremental.sql#L63

  {% for rel in to_drop %}
    {% do adapter.truncate_relation(rel) %}
  {% endfor %}

### Expected Behavior

drop table 

### Steps To Reproduce

1. create model materialized='incremental'

### Environment

```markdown
- OS:MacOs
- Python:3.9
- dbt-core: 1.1.0
```

### What Oracle database version are you using dbt with?

12.1.0

**Comment by aosingh** [comment] 2022-05-27 19:29
Hi @AlexMorti 

Thank you for the detailed bug report. I would like to understand how to reproduce the error `ORA-14452`

In dbt-oracle, temporary tables are named in the following format:

```
    {% set dtstring = dt.strftime("%H%M%S") %}
    {% set tmp_identifier = 'o$pt_' ~ base_relation.identifier ~ dtstring %}
```
So, unless you have multiple dbt sessions at the same time (precisely the same second), you wouldn't get `ORA-14452`

**Comment by AlexMorti** [comment] 2022-05-29 12:08
test model
` {{config(materialized='incremental')}}
select 1 as user_id,
       'test' first_name,
       'test2' last_name
 from dual`

if you remove the exception condition
https://github.com/oracle/dbt-oracle/blob/461f58cd5d079d2ee4eac72dfc9ff09969d8fd7c/dbt/include/oracle/macros/adapters.sql#L262-L263
then there will always be an error:
ORA-14452: attempt to create, alter or drop an index on temporary table already in use
logs attached 
[dbt.log](https://github.com/oracle/dbt-oracle/files/8793292/dbt.log)

**Comment by ThoSap** [comment] 2022-05-30 09:46
> ### Current Behavior
> The global temporary table is not deleted after running the model _due to an_

Hi @AlexMorti, you did not finish this sentence regarding the current behavior.
Are you getting an error, if yes which one?

I had the same issue that the temporary table was not dropped caused by the following issue #8 as the incremental materialization failed due to the ORA errors mentioned in the ticket.

**Comment by aosingh** [comment] 2022-05-31 03:50
@AlexMorti 

Thanks for attaching the logs. I am checking this

**Comment by aosingh** [comment] 2022-06-01 23:17
Hi @AlexMorti 

Could you run dbt without any code changes for an incremental model and share the log ? I would like to understand the ORA errors you get without any code changes. 

Thank you

**Comment by aosingh** [comment] 2022-06-02 15:13
Hi @AlexMorti 

I could reproduce the issue and confirm that `O$PT` tables are only truncated at the end of the dbt session but not dropped. This will be fixed using a TRUNCATE statement before DROPPING the table as you proposed. 

Thank you.

**Closed** 2022-06-15 15:22 UTC
Labels: bug, work-in-progress
